name: Docker compose test

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v1

      - name: Execute docker compose
        run: docker-compose --file config/docker-compose.yml up -d